id = "cem"
name = "Custom Elements Manifest Language Server"
description = "IDE features for custom elements with intelligent autocomplete and hover documentation"
version = "0.7.4"
schema_version = 1
authors = ["Benny Powers <web@bennypowers.com>"]
repository = "https://github.com/bennypowers/cem"

[language_servers.cem-lsp]
name = "CEM Language Server"
languages = ["HTML","TypeScript","JavaScript"]

[language_servers.cem-lsp.binary]
command = "cem"
args = ["lsp", "--stdio"]
